@startuml
actor client
participant SyncThread
database Data
participant Hardware
client -> SyncThread : Create
activate SyncThread
SyncThread -> SyncThread : Initialize
activate SyncThread
SyncThread -> Hardware : Initialize


SyncThread -> Hardware : Read IO
activate Hardware
SyncThread <-- Hardware : Response
deactivate Hardware
SyncThread -> Data : Set Data
client <-- SyncThread : Create completed 
deactivate SyncThread

loop
	SyncThread -> Hardware : Read IO
	activate Hardware
	SyncThread <-- Hardware : Response
	deactivate Hardware
	SyncThread -> Data: Set Input Data
	SyncThread -> Data: Compare Output Data

	alt Saved Data != Hardware Data
		SyncThread -> Hardware : Set Output Data
	else
		note right of SyncThread
			Nothing to do
		end note
	end
    
	client ->> SyncThread : GetInput
	activate SyncThread
	SyncThread -> Data : GetInput
	activate Data
	SyncThread <-- Data : Response
	deactivate Data
	client <<-- SyncThread: Response
	deactivate SyncThread
    
	client ->> SyncThread : SetOutput
	activate SyncThread
	SyncThread -> Data : SetOutput

	
	client <<-- SyncThread
	deactivate SyncThread

end

client -> SyncThread : Terminate
activate SyncThread
SyncThread -> SyncThread : Terminate

SyncThread -x Hardware : Free Ressources
SyncThread -x Data : Free Ressources

deactivate SyncThread
client <-- SyncThread
deactivate SyncThread
deactivate SyncThread

client -x SyncThread : dispose
@enduml
